- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.7.1
  hooks:
    - id: trailing-whitespace
      exclude: ^app/styles/plugins/
    - id: end-of-file-fixer
      exclude: ^app/styles/plugins/
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: check-yaml
-   repo: https://github.com/awebdeveloper/pre-commit-prettier
    sha: 'd4a4c0c'  # Use the sha or tag you want to point at
    hooks:
    -   id: prettier
        additional_dependencies: ['prettier@1.1.0']
        exclude: ^app/styles/plugins/|jquery-3.1.1.min.js
