language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/travis'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
