version: 2
jobs:
  build:
    docker:
      # Recursive self-reference...
      - image: hbpmip/docker-compose-for-ci:17.06-1
    environment:
      - CIRCLECI: true
    steps:
      - checkout
      - run:
        name: echo "A First hello"
      - run:
        name: "Install requirements"
        command: |
          docker --version
  test:
    docker:
      - image: hbpmip/docker-compose-for-ci:17.06-1
    environment:
          - CIRCLECI: true
    steps:
      - checkout
      - run:
        name: echo "A second hello"
      - run:
        name: "Install requirements"
        command: |
          docker --version
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
