version: 2
jobs:
  build:
    docker:
      - image: hbpmip/docker-compose-for-ci:17.06-1
    steps:
      - checkout
      - run:
        name: "First run"
        command: |
         echo "A First hello"
  test:
    docker:
      - image: hbpmip/docker-compose-for-ci:17.06-1
    steps:
      - checkout
      - run:
        name: "Second run"
        command: |
         echo "A second hello"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
