version: 2
jobs:
  tests:
    docker:
      -image: hbpmip/docker-compose-for-ci:17.06-1
    steps:
      - setup_remote_docker:
        version: 17.06.0-ce
      - checkout
      - run:
        name: "Install requirements"
        command: |
          docker --version
      - run:
        name: "Some task in test job"
        command: |
          echo "A second hello"
