version: 2
jobs:
  build:
    docker:
      # Recursive self-reference...
      - image: hbpmip/docker-compose-for-ci:17.06-1
    environment:
      - CIRCLECI: true
    steps:
      - setup_remote_docker:
          version: 17.06.0-ce
      - checkout
      - run: echo "A First hello"
      - run:
          name: "Install requirements"
          command: |
            docker --version
  test:
    docker:
      - image: hbpmip/docker-compose-for-ci:17.06-1
      - image: zookeeper:3.4.11
        environment:
          ZOO_MY_ID: 1
          ZOO_SERVERS: server.1=zookeeper:2888:3888
      - image: mesosphere/mesos-master:1.3.0
        environment:
          MESOS_PORT: 5050
          MESOS_ZK: 'zk://zookeeper:2181/mesos'
          MESOS_QUORUM: '1'
          MESOS_REGISTRY: 'in_memory'
          MESOS_CLUSTER: 'local'
          MESOS_HOSTNAME: 'mesosmaster.docker'
          MESOS_LOG_DIR: '/var/log/mesos/master'
          MESOS_WORK_DIR: '/var/lib/mesos'
    environment:
          - CIRCLECI: true
    steps:
      - checkout
      - run:
          name: "Install requirements"
          command: |
            docker --version
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
