version: 2
machine:
  services:
    - docker
jobs:
  build:
    steps:
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: "Validate code quality"
          command: |
            pre-commit run --all-files
      - run:
          name: "Build project"
          command: |
            PATH=$PATH:/$HOME/.captain/bin/ ./build.sh
    notify:
      webhooks:
      - url: 'https://webhook.atomist.com/atomist/circle'
