jobs:
  build:
    steps:
      - setup_remote_docker:
          version: 17.06.0-ce
machine:
  services:
    - docker
dependencies:
  cache_directories:
    - "~/.npm"
  override:
    - docker info
    - docker build -t hbpmip/portal-frontend .

#test:
#  pre:
#    - ./tests/pre-test-run.sh
#  override:
#    - ./tests/test-run.sh
# deployment:
#   hub:
#     branch: master
#     commands:
#       - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS -e $DOCKER_HUB_EMAIL
#       - docker push --branch-tags=false --commit-tags=true
#       - mvn sonar:sonar -Dsonar.login=$SONAR_KEY  # Need SonarQube back on a public URL
