version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: 'Build frontend'
          command: |
            docker build -t hbpmip/portal-frontend .

  test:
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: "Pull & install backend"
          command: |
            git clone https://github.com/HBPMedical/web-analytics-demo.git
            cd web-analytics-demo
            sh run.sh
      - run:
          name: "Build frontend"
          command: |
            docker build -t hbpmip/portal-frontend:test -f Dockerfile-test .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
