version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: 'Build frontend'
          command: |
            docker build -t hbpmip/portal-frontend .
  test:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: 'Test frontend'
          command: |
            ./run-test.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
