version: 2
jobs:
  build:
    docker:
      - image: hbpmip/docker-compose-for-ci:latest
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: 'Build frontend'
          command: |
            docker build -t hbpmip/portal-frontend .


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
