version: 2
jobs:
  build:
    docker:
      - image: hbpmip/docker-compose-for-ci:17.06-1
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.06.0-ce
      - checkout
      - run: echo "A First hello"
      - run:
          name: 'Install requirements'
          command: |
            docker --version
      - run:
          name: 'Build the project'
          command: |
            docker build -t hbpmip/portal-frontend .


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
