version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: 'Build frontend'
          command: |
            docker build -t hbpmip/portal-frontend .

  test:
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export HOST="CircleCI"' >> $BASH_ENV
      - run:
          name: 'Pull & install backend'
          command: |
            cd ./.circleci/server
            ./ci.sh
      - run:
          name: 'Build frontend'
          command: |
            cd ~/project # cd $CIRCLE_WORKING_DIRECTORY
            docker build -t frontend:test -f Dockerfile-test .
      - run:
          name: 'Test frontend'
          command: |
            docker run -e CI=true -e BACKEND_URL="http://$(hostname):8080" frontend:test yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
