version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: 'Build frontend'
          command: |
            docker build -t hbpmip/portal-frontend .

  test:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: 'Pull & install backend'
          command: |
            cd ./.circleci/server
            ./ci.sh
      - run:
          name: 'Build frontend'
          command: |
            cd ~/project; # cd $CIRCLE_WORKING_DIRECTORY
            docker build -t frontend:test -f Dockerfile-test .
      - run:
          name: 'Test frontend'
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt update
            sudo apt install yarn
            echo REACT_APP_BACKEND_URL = \"http://$(hostname)\" | tee .env
            yarn install
            yarn test --ci --watchAll

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
