version: '3.2'

networks:
  frontend:
  backend:

services:
  exareme-keystore:
    image: progrium/consul
    command:
      - -server
      - -bootstrap
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager # Ensures we only start on manager nodes
          # - node.labels.name == ${HOSTNAME}
    ports:
      - '8500:8500'
    networks:
      backend:

  exareme-master:
    image: hbpmip/exareme:v21.3.0
    environment:
      - CONSULURL=miplocal_exareme-keystore:8500
      - MASTER_FLAG=master
      - NODE_NAME=miplocal
      - DOCKER_DATA_FOLDER=/root/exareme/data/
      - DOCKER_METADATA_FOLDER=/root/exareme/data/
      - EXAREME_ACTIVE_WORKERS_PATH=active_workers
      - EXAREME_MASTER_PATH=master
      - DATA=data
    depends_on:
      - miplocal_exareme-keystore
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager # Ensures we only start on manager nodes
    ports:
      - '9090:9090'
    volumes:
      - ./data:/root/exareme/data/
    networks:
      backend:

  db:
    image: postgres:11.3-alpine
    ports:
      - '5432:5432'
    hostname: db
    environment:
      POSTGRES_PASSWORD: test
    networks:
      backend:

  wait_dbs:
    image: 'waisbrot/wait'
    environment:
      TARGETS: 'db:5432'
      TIMEOUT: 60
    depends_on:
      - db
    networks:
      backend:

  create_dbs:
    image: 'hbpmip/create-databases:1.1.0'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_ADMIN_USER: postgres
      DB_ADMIN_PASSWORD: test
      DB4: portal
      USER4: portal
      PASSWORD4: portalpwd
    depends_on:
      - db
    networks:
      backend:

  portalbackend:
    image: hbpmip/portal-backend:dev_v6.0.0
    ports:
      - '8080:8080'
      - '8089:8089'
    environment:
      PORTAL_DB_URL: jdbc:postgresql://db:5432/portal
      PORTAL_DB_SERVER: db:5432
      PORTAL_DB_USER: portal
      PORTAL_DB_PASSWORD: portalpwd
      CONTEXT_PATH: /services
      AUTHENTICATION: 0
      CLIENT_ID: medical-informatics-platform
      CLIENT_SECRET: dae83a6b-c769-4186-8383-f0984c6edf05
      FRONTEND_LOGIN_URL: http://88.197.53.106/services/login/hbp
      FRONTEND_AFTER_LOGIN_URL: http://88.197.53.106/
      FRONTEND_AFTER_LOGOUT_URL: http://88.197.53.106/services/login/hbp
      LOGGING_LEVEL_WEB: INFO
      LOGGING_LEVEL_HIBERNATE: INFO
      SESSION_TIMEOUT: 2592000
      RELEASE_STAGE: 'testing'
      DATACENTER_LOCATION: '$HOST'
      CONTAINER_ORCHESTRATION: 'docker-compose'

      EXAREME_URL: mip_local-exareme-master:9090

      GALAXY_URL: 'http://88.197.53.106:8090/nativeGalaxy'
      GALAXY_CONTEXT: nativeGalaxy/workflows/list
      GALAXY_API_KEY: 'd14a4cc5eebf805eb2ff261374ed08a2'
      GALAXY_USERNAME: admin
      GALAXY_PASSWORD: password

      KEYCLOAK_URL: '88.197.53.106'
      AUTH_URI: 'https://88.197.53.106:8095/auth/realms/MIP/protocol/openid-connect/auth'
      USER_INFO_URI: 'https://88.197.53.106:8095/auth/realms/MIP/protocol/openid-connect/userinfo'
      TOKEN_URI: 'https://88.197.53.106:8095/auth/realms/MIP/protocol/openid-connect/token'
      LOGOUT_URI: 'https://88.197.53.106:8095/auth/realms/MIP/protocol/openid-connect/logout'

    depends_on:
      - db
    volumes:
      - ./data:/opt/portal/api
      - ./logs:/opt/portal/logs
    networks:
      backend:
      frontend:

  wait_portal_backend:
    image: 'waisbrot/wait'
    environment:
      TARGETS: 'portalbackend:8080'
      TIMEOUT: 60
    depends_on:
      - portalbackend
    networks:
      backend:

  frontend:
    image: hbpmip/portal-frontend:dev_5.2.0
    depends_on:
      - portalbackend
    ports:
      - '80:80'
    environment:
      WORKER_PROCESSES: 1
      ERROR_LOG_LEVEL: warn
      PORTAL_VIRTUAL_HOST: frontend
      PORTAL_BACKEND_SERVER: portalbackend:8080
      PORTAL_BACKEND_CONTEXT: services
      MODE: federation
      INSTANCE_NAME: 'MIP 5.0.0'
      VERSION: '5.0.0'
      TRACKER_ID: UA-80660232-5
      GALAXY_URL: 'http://88.197.53.106:8090/nativeGalaxy'
    networks:
      frontend:
      backend:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      backend:

  keycloak:
    image: jboss/keycloak
    volumes:
      - ./certs:/etc/x509/https
      - ./realms/mip.json:/tmp/mip.json
      - ./tmp:/tmp
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_IMPORT: /tmp/mip.json
    ports:
      - '8095:8095'
      - '8443:8443'
    depends_on:
      - postgres
    networks:
      backend:
