version: '3.2'

networks:
  net-local:
    external:
      name: mip-local

services:
  exareme-keystore:
    image: progrium/consul
    command:
      - -server
      - -bootstrap
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager # Ensures we only start on manager nodes
    networks:
      - 'net-local' # Connect the docker container to the global network
    ports:
      - '8500:8500'

  exareme-master:
    image: ${EXAREME_IMAGE}
    environment:
      - CONSULURL=${EXAREME_KEYSTORE}
      - MASTER_FLAG=${FEDERATION_ROLE}
      - NODE_NAME=${FEDERATION_NODE}
      - DOCKER_DATA_FOLDER=${DOCKER_DATA_FOLDER}
      - DOCKER_METADATA_FOLDER=${DOCKER_DATA_FOLDER}
      - EXAREME_ACTIVE_WORKERS_PATH=active_workers
      - EXAREME_MASTER_PATH=master
      - DATASETS=datasets
    depends_on:
      - exareme-keystore
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager # Ensures we only start on manager nodes
    ports:
      - '9090:9090'
    networks:
      - 'net-local' # Connect the docker container to the global network
    volumes:
      - ${LOCAL_DATA_FOLDER}:${DOCKER_DATA_FOLDER}

  db:
    image: postgres:11.3-alpine
    ports:
      - '5432:5432'
    hostname: ${FEDERATION_NODE}
    environment:
      POSTGRES_PASSWORD: test

  create_dbs:
    image: 'hbpmip/create-databases:1.1.0'
    restart: 'no'
    environment:
      DB_HOST: ${FEDERATION_NODE}_db
      DB_PORT: 5432
      DB_ADMIN_USER: postgres
      DB_ADMIN_PASSWORD: test
      DB4: portal
      USER4: portal
      PASSWORD4: portalpwd
    depends_on:
      - ${FEDERATION_NODE}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  portalbackend:
    image: ${BACKEND_IMAGE}
    restart: 'no'
    ports:
      - '8080:8080'
    environment:
      PORTAL_DB_URL: jdbc:postgresql://${FEDERATION_NODE}_db:5432/portal
      PORTAL_DB_SERVER: ${FEDERATION_NODE}_db:5432
      PORTAL_DB_USER: portal
      PORTAL_DB_PASSWORD: portalpwd
      CONTEXT_PATH: /services
      EXAREME_URL: http://${FEDERATION_NODE}:9090
      AUTHENTICATION: 0
      FRONTEND_LOGIN_URL: ${FRONTEND_URL}/services/login/hbp
      FRONTEND_AFTER_LOGIN_URL: ${FRONTEND_URL}/
      FRONTEND_AFTER_LOGOUT_URL: ${FRONTEND_URL}/services/login/hbp
      SESSION_TIMEOUT: 2592000
      RELEASE_STAGE: 'testing'
    depends_on:
      - db
    volumes:
      - ./data:/opt/portal/api
  # frontend:
  #   image: ${FRONTEND_IMAGE}
  #   depends_on:
  #     - portalbackend
  #   ports:
  #     - '80:80'
  #   environment:
  #     WORKER_PROCESSES: 1
  #     ERROR_LOG_LEVEL: warn
  #     PORTAL_VIRTUAL_HOST: frontend
  #     PORTAL_BACKEND_SERVER: ${FEDERATION_NODE}_portalbackend:8080
  #     PORTAL_BACKEND_CONTEXT: services
  #     MODE: local
  #     INSTANCE_NAME: 'MIP 5.0.0'
  #     VERSION: '5.0.0'
  #     TRACKER_ID: UA-80660232-5
  #     GALAXY_URL: http://127.0.0.1:8090/nativeGalaxy
