# This workflow is used to test build capability
name: Build image

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup docker
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Run build
        run: docker build -t hbpmip/portal-frontend:pipe-ci .
