# This workflow is used to test build capability
name: Build image

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Release Type
        required: true
        default: patch
        options:
          - "major"
          - "minor"
          - "patch"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup docker
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login - u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

      - name: Major release
        if: github.event.inputs.release-type == 'major'
        run: echo '1' | ./publish.sh

      - name: Minor release
        if: github.event.inputs.release-type == 'minor'
        run: echo '2' | ./publish.sh

      - name: Patch release
        if: github.event.inputs.release-type == 'patch'
        run: echo '3' | ./publish.sh
