# This workflow will do a clean install and will test the frontend service

name: Unit tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Yarn
        run: npm i -g yarn

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Launch unit tests
        run: yarn ci-test
